name: AdvAttacks
channels:
  - conda-forge
dependencies:
  - python=3.12.9
  - anaconda
  - pip
  - pip:
      - --index-url=https://download.pytorch.org/whl/cu118
      - torch==2.2.0+cu118
      - torchvision==0.17.0+cu118
      - -r requirements.txt
