name: AdvAttacks
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11.9
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=11.8
  - numpy=1.26.4
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - sympy=1.13.1
  - tqdm=4.67.0
  - datasets=3.6.0
  - statsmodels=0.14.4
  - wandb=0.20.1
  - scipy=1.13.0