name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install test dependencies
      run: |
        pip install pillow
        
    - name: Verify test assets exist
      run: |
        ls -la tests/assets/
        test -f tests/assets/bird_original.png || (echo "Missing bird_original.png" && exit 1)
        test -f tests/assets/bird_perturbed.png || (echo "Missing bird_perturbed.png" && exit 1)
        
    - name: Test with unittest
      run: |
        python -m unittest discover tests -p "*_test.py"
        
    - name: Display test results summary
      if: always()
      run: |
        echo "Test execution completed. Check logs above for detailed results." 